INSERT INTO public.atletas (nome,imagem_url,descricao) VALUES
	 ('Beatriz Ferreira ','https://www.olimpiadatododia.com.br/wp-content/uploads/2019/08/Beatriz-Ferreira-Bia-Ferreira-Boxe-Lima-2019-Jonne-RorizCOB.jpg','Campeã mundial e dos Jogos Pan-Americanos em 2019, Beatriz Ferreira é o grande nome do Brasil. Vamos lá, Beatriz!!!!! Força Brasil!!! '),
	 ('Nathalie Moellhausen ','https://www.olimpiadatododia.com.br/wp-content/uploads/2019/07/Nathalie-Moellhausen-leva-Brasil-ao-primeiro-t%C3%ADtulo-Mundial.jpg',' A campeã mundial Nathalie Moellhausen vai representar o Brasil em Tóquio! Estamos torcendo por você!'),
	 ('Futebol Feminino','https://lilianpacce.s3.amazonaws.com/wp-content/uploads/2016/08/230816-futebol-feminino-wanderley-nunes-2.jpg','A Seleção Brasileira de futebol feminino garantiu a classificação com a conquista do hexacampeonato da Copa América, em abril de 2018. Para chegar ao título, o Brasil venceu todas as sete partidas que disputou.'),
	 ('Futebol Masculino','https://veja.abril.com.br/wp-content/uploads/2016/08/ouro-brasil-016.jpg','A equipe comandada por André Jardim terminou a competição invicta com seis vitórias e dois empates. Na última rodada, os brasileiros carimbaram a faixa da campeã Argentina com uma vitória por 3 a 0.'),
	 ('Flavia Saraiva','https://www.olimpiadatododia.com.br/wp-content/uploads/2019/10/flavia-saraiva-final-ind-geral-barras-assimetricas-mundial-alemanha.jpg','Flávia Saraiva vai disputar em Tóquio a segunda Olimpíada de sua carreira'),
	 ('Paulo André Camilo de Oliveira','https://www.olimpiadatododia.com.br/wp-content/uploads/2019/09/Paulo-Andr%C3%A9-Mundial-de-Atletismo.jpg','Paulo André garantiu índice para os Jogos Olímpicos nos 100m rasos '),
	 ('Ginastica Rítmica ','https://www.olimpiadatododia.com.br/wp-content/uploads/2021/06/Design-sem-nome-1.jpg','O conjunto brasileiro de ginástica rítmica garantiu cinco vagas nos Jogos Olímpicos de Tóquio ao conquistarem o título do Pan-Americano da modalidade.'),
	 ('Handebol Feminino','https://www.olimpiadatododia.com.br/wp-content/uploads/2019/07/Ap%C3%B3s-Lima-Duda-Amorim-garante-o-Mundial-%C3%A9-chave-para-n%C3%B3s.jpg','A Seleção Brasileira de handebol feminino se classificou para a Olimpíada de Tóquio com a conquista do hexacampeonato dos Jogos Pan-Americanos. A medalha de ouro veio com autoridade com uma vitória das brasileiras por 30 a 21 sobre a Argentina.'),
	 ('Handebol Masculino ','https://www.olimpiadatododia.com.br/wp-content/uploads/2021/03/159935039_922947968479669_1562495710022303432_n.jpg','A seleção brasileira de handebol masculino se classificou para os Jogos de Tóquio ao ficar em segundo lugar no Pré-Olímpico disputado em Montenegro.'),
	 ('Hipismo CCE ','https://www.olimpiadatododia.com.br/wp-content/uploads/2019/08/carlos-parro-cce-lima-1024x682.jpg','A conquista das quatro vagas no Conjunto Completo de Equitação veio com a medalha de prata por equipes nos Jogos Pan-Americanos. Carlos Parro Marcelo Tosi Rafael Losano');
INSERT INTO public.atletas (nome,imagem_url,descricao) VALUES
	 ('Hipismo Salto ','https://www.olimpiadatododia.com.br/wp-content/uploads/2019/07/Jogos-Pan-Americanos-Lima-2019-Hipismo-Saltos-por-equipes-3.jpg','A medalha de ouro por equipes nos Jogos Pan-Americanos fez com que quatro atletas brasileiros fossem classificados para os Jogos Olímpicos de Tóquio.Luiz Francisco Azevedo Marlon Zanotelli Rodrigo Pessoa Yuri Mansur'),
	 ('Fernando Reis ','https://www.olimpiadatododia.com.br/wp-content/uploads/2017/12/Fernando-Reis-2.jpg','Fernando Reis (+109kg masculino) e Jaqueline Ferreira (87kg feminino) são os brasileiros classificados no levantamento de peso para os Jogos Olímpicos.'),
	 ('Italo Ferreira ','https://www.olimpiadatododia.com.br/wp-content/uploads/2019/12/italo-ferreira-campeao-wsl-trofeu.jpg','Atual campeão mundial, Ítalo Ferreira estará em Tóquio! Força, Italo! '),
	 ('Volei Feminino ','https://www.olimpiadatododia.com.br/wp-content/uploads/2019/09/brasil-rep-dominicanan-copa-do-mundo-volei-feminino.jpg','O Brasil carimbou o passaporte para ir a Tóquio ao vencer Camarões, República Domincana e Azerbaijão no Pré-Olímpico em 2019. Depois do do vice-campeonato da Liga das Nações em 2021, José Roberto Guimarães definiu as convocadas!'),
	 ('Volei Masculino ','https://www.olimpiadatododia.com.br/wp-content/uploads/2019/10/brasil-italia-festa-jogadores-copa-mundo.jpg','Foi suado! No Pré-Olímpico masculino, o Brasil só conseguiu a classificação para os Jogos Olímpicos depois de uma batalha contra a Bulgária. A equipe estava perdendo por 2 a 0 para os búlgaros, mas conseguiu a virada e venceu por 3 a 2.');